security:
  basic:
    enabled: false # turn of securing our application endpoints

management:
  security:
    enabled: false # turn of securing the actuator endpoints
logging: # <----New sections below
  level:
    io:
      pivotal: INFO

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
